import { StyleSheet } from 'react-native';

const signupStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  tabContainer: {
    flexDirection: 'row',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1,
    padding: 15,
  },
  tab: {
    flex: 1,
    padding: 10,
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
    borderBottomColor: '#ccc',
  },
  activeTab: {
    borderBottomColor: '#059033',
  },
  tabText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  input: {
    width: '80%',
    padding: 10,
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
    marginVertical: 10,
    fontSize: 16,
    paddingLeft: 15,
  },
  checkboxContainer: {
    flexDirection: 'row',
    marginTop: 20,
    marginBottom: 5,
    alignSelf: 'flex-start',
    marginLeft: '10%',
  },
  checkbox: {
    width: 25,
    height: 25,
    borderWidth: 1,
    borderColor: '#ccc',
    justifyContent: 'left',
    alignItems: 'left',
    marginRight: 10,
    borderRadius: 15,
  },
  checkboxChecked: {
    backgroundColor: '#059033',
  },
  checkboxText: {
    color: 'white',
  },
  label: {
    margin: 2,
  },
  signup_btn: {
    backgroundColor: '#059033',
    color: 'white',
    padding: 10,
    textAlign: 'center',
    borderRadius: 5,
    marginTop: 50,
    fontSize: 15,
    fontWeight: 'bold',
  },
  reset_btn: {
    backgroundColor: '#059033',
    color: 'white',
    padding: 10,
    textAlign: 'center',
    borderRadius: 5,
    marginTop: 50,
    fontSize: 15,
    fontWeight: 'bold',
  },
});

const loginStyles = StyleSheet.create({
  background: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    width: 380,
    height: 500,
    backgroundColor: 'rgba(255, 255, 255, 1)',
    borderRadius: 25,
    alignItems: 'center',
  },
  input: {
    margin: 10,
    height: 60,
    width: 300,
    borderColor: 'black',
    borderWidth: 1,
    borderRadius: 10,
    paddingLeft: 15,
    fontSize: 18,
  },
  header: {
    width: 1000,
    height: 100,
    backgroundColor: '#3f6ff0',
    justifyContent: 'center',
    paddingLeft: 50,
    marginBottom: 30,
  },
  button: {
    justifyContent: 'center',
    alignItems: 'center',
    margin: 25,
    marginBottom: 15,
  },
  f_button: {
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: '#059033',
    borderRadius: 15,
    fontSize: 20,
    backgroundColor: '#059033',
    overflow: 'hidden',
    width: 250,
    textAlign: 'center',
  },
  control: {
    backgroundColor: '#059033',
    marginTop: 10,
    marginBottom: 50,
    width: 250,
    left: 90,
    borderColor: '#059033',
    borderWidth: 1,
    borderRadius: 15,
  },
  on_off: {
    top: 80,
    left: 25,
    position: 'absolute',
    fontSize: 20,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 80,
    marginTop: 0,
    color: 'darkgreen',
  },
  start_btn: {
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderWidth: 1,
    borderColor: '#059033',
    borderRadius: 15,
    color: 'white',
    fontSize: 20,
    backgroundColor: '#059033',
    overflow: 'hidden',
  },
  login_btn: {
    marginBottom: 80,
    marginTop: 40,
    padding: 10,
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 10,
    color: 'white',
    fontSize: 20,
    backgroundColor: '#059033',
    overflow: 'hidden',
    width: 150,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  con_button: {
    color: 'darkgreen',
    fontSize: 15,
    fontWeight: 'bold',
  },
});

export { loginStyles, signupStyles };
