import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  background: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    width: 380,
    height: 500,
    backgroundColor: 'rgba(255, 255, 255, 1)',
    borderRadius: 25,
    alignItems: 'center',
  },
  input: {
    margin: 10,
    height: 60,
    width: 300,
    borderColor: '#bcbcbc',
    borderWidth: 1,
    borderRadius: 10,
    paddingLeft: 15,
    fontSize: 18,
  },
  header: {
    width: 1000,
    height: 100,
    backgroundColor: '#3f6ff0',
    justifyContent: 'center',
    paddingLeft: 50,
    marginBottom: 30,
  },
  button: {
    justifyContent: 'center',
    alignItems: 'center',
    margin: 25,
    marginBottom: 15,
  },
  f_button: {
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: '#059033',
    borderRadius: 15,
    fontSize: 20,
    backgroundColor: '#059033',
    overflow: 'hidden',
    width: 250,
    textAlign: 'center',
  },
  control: {
    backgroundColor: '#059033',
    marginTop: 10,
    marginBottom: 50,
    width: 250,
    left: 90,
    borderColor: '#059033',
    borderWidth: 1,
    borderRadius: 15,
  },
  on_off: {
    top: 80,
    left: 25,
    position: 'absolute',
    fontSize: 20,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 80,
    marginTop: 0,
    color: 'darkgreen',
  },
  start_btn: {
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderWidth: 1,
    borderColor: '#059033',
    borderRadius: 15,
    color: 'white',
    fontSize: 20,
    backgroundColor: '#059033',
    overflow: 'hidden',
  },
  login_btn: {
    marginBottom: 50,
    marginTop: 50,
    padding: 10,
    borderWidth: 1,
    borderColor: '#059033',
    borderRadius: 10,
    color: 'white',
    fontSize: 20,
    backgroundColor: '#059033',
    overflow: 'hidden',
    width: 150,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  con_button: {
    color: 'darkgreen',
    fontSize: 16,
    textDecorationLine: 'underline',
    fontWeight: 'bold',
  },
});

export default styles;